In [1]:
#!pip install -e [extra]
#!pip install tensorboard
!pip install tensorflow
!pip install git+https://github.com/carlosluis/stable-baselines3@fix_tests 
!pip install pyglet
!pip install gym['classic_control']
#pip install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance
#!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 805.3 kB/s eta 0:00:0000:0100:05
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 3.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 3.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.5/21.5 MB 3.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 6.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 3.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 1.2 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 3.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

In [2]:
import os
import gym
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
%load_ext tensorboard

In [3]:
os.environ["SDL_VIDEODRIVER"] = "dummy"

In [8]:
environment_name = 'CartPole-v1'
env = gym.make(environment_name)
environment_name

'CartPole-v1'

In [9]:
episodes=10
for episode in range(1, episodes+1):
    state = env.reset()
    truncated = False
    score = 0
    while not truncated:
        env.render()
        action = env.action_space.sample()
        next_state, reward, terminated, truncated , info = env.step(action)
        score += reward
    print('Episone:{} Score:{}'.format( episode, score))
env.close()    

/opt/conda/lib/python3.10/site-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(


Episone:1 Score:29.0
Episone:2 Score:32.0
Episone:3 Score:22.0
Episone:4 Score:17.0
Episone:5 Score:31.0
Episone:6 Score:12.0
Episone:7 Score:24.0
Episone:8 Score:21.0
Episone:9 Score:16.0
Episone:10 Score:13.0


In [10]:
env.observation_space.sample()

array([ 8.2398462e-01,  2.7396842e+38,  5.6978744e-02, -1.8523515e+38],
      dtype=float32)

In [11]:
env.reset()

(array([ 0.02688016, -0.02007901, -0.01611588, -0.01492143], dtype=float32),
 {})

In [12]:
env.action_space.sample(), env.action_space

(0, Discrete(2))

In [13]:
env.step(1)

(array([ 0.02647858,  0.17527032, -0.01641431, -0.31264523], dtype=float32),
 1.0,
 False,
 False,
 {})

In [14]:
env.action_space

Discrete(2)

In [15]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [16]:
log_path = os.path.join('training','logs')
log_path

'training/logs'

In [17]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [18]:
model.learn(total_timesteps=20000)

2023-02-28 17:04:29.090383: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 17:04:35.520592: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-28 17:04:35.521574: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-28 17:04:35.521622: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nv

Logging to training/logs/PPO_9
-----------------------------
| time/              |      |
|    fps             | 102  |
|    iterations      | 1    |
|    time_elapsed    | 19   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 126         |
|    iterations           | 2           |
|    time_elapsed         | 32          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008716082 |
|    clip_fraction        | 0.0784      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.687      |
|    explained_variance   | -0.00133    |
|    learning_rate        | 0.0003      |
|    loss                 | 7.88        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0123     |
|    value_loss           | 55.1        |
-----------------------------------------
---

In [19]:
PPO_Path = os.path.join('training','save','PPO_Model_Cartpole')
PPO_Path

'training/save/PPO_Model_Cartpole'

In [20]:
model.save(PPO_Path)

In [21]:
del model

In [22]:
model = PPO.load(PPO_Path, env=env)

In [23]:
evaluate_policy(model, env, n_eval_episodes=20, render=True)

/opt/conda/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:208: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


(492.5, 19.744619520264248)

In [24]:
env.close()

In [25]:
episodes=10
for episode in range(1, episodes+1):
    observation = env.reset()
    terminated = False
    score = 0
    while not terminated:
        env.render()
        action, _ = model.predict(observation)
        observation, reward, terminated , info = env.step(action)
        score += reward
    print('Episone:{} Score:{}'.format( episode, score))
env.close()    

Episone:1 Score:[327.]
Episone:2 Score:[283.]
Episone:3 Score:[257.]
Episone:4 Score:[418.]
Episone:5 Score:[500.]
Episone:6 Score:[451.]
Episone:7 Score:[500.]
Episone:8 Score:[500.]
Episone:9 Score:[500.]
Episone:10 Score:[233.]


In [26]:
log_path

'training/logs'

In [27]:
training_log_path = os.path.join('./', log_path)
training_log_path = training_log_path + '/'
training_log_path

'./training/logs/'

In [ ]:
#%tensorboard --logdir training_log_path --max_reload_threads 4
#!tensorboard --logdir './training/logs/PPO_3/' --bind_all
#!tensorboard --logdir ./ --bind_all
!tensorboard --logdir './training/logs/' --bind_all  # training_log_path

2023-02-28 17:16:03.037919: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 17:16:03.934190: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-28 17:16:03.934894: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-28 17:16:10.247486: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [25]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [31]:
save_path = os.path.join('training','save')

In [32]:
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)
eval_callback = EvalCallback(env,
                             callback_on_new_best=stop_callback,
                             eval_freq=10000,
                             best_model_save_path=save_path,
                             verbose=1)

In [34]:
log_path, save_path

('training/logs', 'training/save')

In [35]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [36]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to training/logs/PPO_6
-----------------------------
| time/              |      |
|    fps             | 156  |
|    iterations      | 1    |
|    time_elapsed    | 13   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 2           |
|    time_elapsed         | 35          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008752664 |
|    clip_fraction        | 0.116       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | 0.00169     |
|    learning_rate        | 0.0003      |
|    loss                 | 5.63        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0177     |
|    value_loss           | 47.8        |
-----------------------------------------
---

In [37]:
!tensorboard --logdir './training/logs/' --bind_all

2023-02-24 03:56:15.908507: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-24 03:56:16.640335: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-24 03:56:16.640548: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-24 03:56:21.897803: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [61]:
net_arch = dict(pi=[128,128,128,128], vf=[128,128,128,128])

In [62]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path, policy_kwargs={'net_arch':net_arch})

Using cpu device


In [63]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to training/logs/PPO_6
-----------------------------
| time/              |      |
|    fps             | 140  |
|    iterations      | 1    |
|    time_elapsed    | 14   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 80          |
|    iterations           | 2           |
|    time_elapsed         | 50          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.015254676 |
|    clip_fraction        | 0.219       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | 0.00129     |
|    learning_rate        | 0.0003      |
|    loss                 | 5.13        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0255     |
|    value_loss           | 24.6        |
-----------------------------------------
---

In [65]:
from stable_baselines3 import DQN

In [66]:
model = DQN('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [67]:
model.learn(total_timesteps=20000)

Logging to training/logs/DQN_1
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.968    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 344      |
|    time_elapsed     | 0        |
|    total_timesteps  | 67       |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.918    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 557      |
|    time_elapsed     | 0        |
|    total_timesteps  | 173      |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.865    |
| time/               |          |
|    episodes         | 12       |
|    fps              | 508      |
|    time_elapsed     | 0        |
|    total_timesteps  | 285      |
----------------------------------
------------------------

In [69]:
DQN_Path = os.path.join('training','save','DQN_Model_Cartpole')
DQN_Path

'training/save/DQN_Model_Cartpole'

In [70]:
model.save(DQN_Path)

In [71]:
del model

In [74]:
model = DQN.load(DQN_Path, env=env)

In [75]:
del model