In [1]:
#!pip install -e [extra]
#!pip install tensorboard
!pip install tensorflow
!pip install git+https://github.com/carlosluis/stable-baselines3@fix_tests 
!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 581.3 kB/s eta 0:00:0000:0100:08
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 1.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 614.4 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.5/21.5 MB 1.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 1.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 1.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 1.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 1.3 MB/s eta 0:00:0000:0100:010m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 1.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━

In [2]:
import os
import gym
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
%load_ext tensorboard

In [3]:
#pip install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance

In [4]:
environment_name = 'CartPole-v0'
env = gym.make(environment_name)
environment_name

/opt/conda/lib/python3.10/site-packages/gym/envs/registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(


'CartPole-v0'

In [5]:
episodes=10
for episode in range(1, episodes+1):
    state = env.reset()
    truncated = False
    score = 0
    while not truncated:
        env.render()
        action = env.action_space.sample()
        next_state, reward, terminated, truncated , info = env.step(action)
        score += reward
    print('Episone:{} Score:{}'.format( episode, score))
env.close()    

/opt/conda/lib/python3.10/site-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v0", render_mode="rgb_array")
  gym.logger.warn(
/opt/conda/lib/python3.10/site-packages/gym/envs/classic_control/cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


Episone:1 Score:52.0
Episone:2 Score:15.0
Episone:3 Score:49.0
Episone:4 Score:14.0
Episone:5 Score:20.0
Episone:6 Score:14.0
Episone:7 Score:12.0
Episone:8 Score:18.0
Episone:9 Score:11.0
Episone:10 Score:23.0


In [6]:
env.observation_space.sample()

array([4.4960976e+00, 2.4203725e+38, 6.5733775e-02, 1.8210087e+38],
      dtype=float32)

In [7]:
env.reset()

(array([-0.030233  , -0.02801931, -0.0012115 ,  0.01184139], dtype=float32),
 {})

In [8]:
env.action_space.sample(), env.action_space

(0, Discrete(2))

In [9]:
env.step(1)

(array([-0.03079339,  0.16712   , -0.00097467, -0.28122354], dtype=float32),
 1.0,
 False,
 False,
 {})

In [10]:
env.action_space

Discrete(2)

In [11]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [12]:
log_path = os.path.join('training','logs')
log_path

'training/logs'

In [13]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [16]:
model.learn(total_timesteps=20000)

Logging to training/logs/PPO_2
-----------------------------
| time/              |      |
|    fps             | 203  |
|    iterations      | 1    |
|    time_elapsed    | 10   |
|    total_timesteps | 2048 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 139          |
|    iterations           | 2            |
|    time_elapsed         | 29           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0061561153 |
|    clip_fraction        | 0.0358       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.549       |
|    explained_variance   | 0.0424       |
|    learning_rate        | 0.0003       |
|    loss                 | 0.682        |
|    n_updates            | 110          |
|    policy_gradient_loss | -0.00187     |
|    value_loss           | 5.78         |
----------------------------

In [17]:
PPO_Path = os.path.join('training','save','PPO_Model_Cartpole')
PPO_Path

'training/save/PPO_Model_Cartpole'

In [18]:
model.save(PPO_Path)

In [19]:
del model

In [20]:
model = PPO.load(PPO_Path, env=env)

In [21]:
evaluate_policy(model, env, n_eval_episodes=20, render=True)

/opt/conda/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:208: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


(200.0, 0.0)

In [27]:
env.close()

In [28]:
episodes=10
for episode in range(1, episodes+1):
    observation = env.reset()
    terminated = False
    score = 0
    while not terminated:
        env.render()
        action, _ = model.predict(observation)
        observation, reward, terminated , info = env.step(action)
        score += reward
    print('Episone:{} Score:{}'.format( episode, score))
env.close()    

/opt/conda/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:208: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


Episone:1 Score:[200.]
Episone:2 Score:[200.]
Episone:3 Score:[200.]
Episone:4 Score:[200.]
Episone:5 Score:[200.]
Episone:6 Score:[200.]
Episone:7 Score:[200.]
Episone:8 Score:[200.]
Episone:9 Score:[200.]
Episone:10 Score:[200.]


In [29]:
training_log_path = os.path.join(log_path, 'PPO_1')
training_log_path

'training/logs/PPO_1'

In [30]:
%tensorboard --logdir training_log_path

Reusing TensorBoard on port 6006 (pid 5227), started 0:01:21 ago. (Use '!kill 5227' to kill it.)