In [1]:
#!pip install -e [extra]
#!pip install tensorboard
!pip install tensorflow
!pip install git+https://github.com/carlosluis/stable-baselines3@fix_tests 
!pip install pyglet
!pip install gym['classic_control']
#pip install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance
#!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 805.3 kB/s eta 0:00:0000:0100:05
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 3.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 3.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.5/21.5 MB 3.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 6.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 3.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 1.2 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 3.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

In [2]:
import os
import gym
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
%load_ext tensorboard

In [3]:
os.environ["SDL_VIDEODRIVER"] = "dummy"

In [4]:
environment_name = 'CartPole-v1'
env = gym.make(environment_name)
environment_name

'CartPole-v1'

In [15]:
episodes=10
for episode in range(1, episodes+1):
    state = env.reset()
    terminated = False
    score = 0
    while not terminated:
        #env.render()
        action = env.action_space.sample()
        #print(env.step(action))
        next_state, reward, terminated, truncated, info = env.step(action)
        score += reward
    print('Episone:{} Score:{}'.format( episode, score))
env.close()    

Episone:1 Score:33.0
Episone:2 Score:23.0
Episone:3 Score:35.0
Episone:4 Score:26.0
Episone:5 Score:24.0
Episone:6 Score:59.0
Episone:7 Score:12.0
Episone:8 Score:23.0
Episone:9 Score:39.0
Episone:10 Score:55.0


In [45]:
env.observation_space.sample()

array([-1.2194368e+00, -2.0894857e+38,  3.2013637e-01, -9.0930663e+36],
      dtype=float32)

In [46]:
env.reset()

(array([ 0.03039081,  0.02335716, -0.00624426,  0.00101587], dtype=float32),
 {})

In [47]:
env.action_space.sample(), env.action_space

(1, Discrete(2))

In [48]:
env.step(1)

(array([ 0.03085796,  0.2185681 , -0.00622394, -0.29363063], dtype=float32),
 1.0,
 False,
 False,
 {})

In [49]:
env.action_space

Discrete(2)

In [50]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [51]:
log_path = os.path.join('training','logs')
log_path

'training/logs'

In [52]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [53]:
model.learn(total_timesteps=20000)

Logging to training/logs/PPO_12
-----------------------------
| time/              |      |
|    fps             | 373  |
|    iterations      | 1    |
|    time_elapsed    | 5    |
|    total_timesteps | 2048 |
-----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 272        |
|    iterations           | 2          |
|    time_elapsed         | 15         |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.00873274 |
|    clip_fraction        | 0.105      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.686     |
|    explained_variance   | 0.00053    |
|    learning_rate        | 0.0003     |
|    loss                 | 7.82       |
|    n_updates            | 10         |
|    policy_gradient_loss | -0.016     |
|    value_loss           | 58.8       |
----------------------------------------
--------------------

In [54]:
PPO_Path = os.path.join('training','save','PPO_Model_Cartpole')
PPO_Path

'training/save/PPO_Model_Cartpole'

In [55]:
model.save(PPO_Path)

In [56]:
del model

In [57]:
model = PPO.load(PPO_Path, env=env)

In [58]:
evaluate_policy(model, env, n_eval_episodes=20, render=True)

(500.0, 0.0)

In [59]:
env.close()

In [60]:
episodes=10
for episode in range(1, episodes+1):
    observation = env.reset()
    terminated = False
    score = 0
    while not terminated:
        env.render()
        action, _ = model.predict(observation)
        observation, reward, terminated , info = env.step(action)
        score += reward
    print('Episone:{} Score:{}'.format( episode, score))
env.close()    

Episone:1 Score:[500.]
Episone:2 Score:[500.]
Episone:3 Score:[500.]
Episone:4 Score:[500.]
Episone:5 Score:[500.]
Episone:6 Score:[500.]
Episone:7 Score:[500.]
Episone:8 Score:[374.]
Episone:9 Score:[500.]
Episone:10 Score:[500.]


In [61]:
log_path

'training/logs'

In [62]:
training_log_path = os.path.join('./', log_path)
training_log_path = training_log_path + '/'
training_log_path

'./training/logs/'

In [28]:
#%tensorboard --logdir training_log_path --max_reload_threads 4
#!tensorboard --logdir './training/logs/PPO_3/' --bind_all
#!tensorboard --logdir ./ --bind_all
!tensorboard --logdir './training/logs/' --bind_all  # training_log_path

2023-02-28 17:16:03.037919: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 17:16:03.934190: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-28 17:16:03.934894: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-28 17:16:10.247486: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [63]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [64]:
save_path = os.path.join('training','save')

In [65]:
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)
eval_callback = EvalCallback(env,
                             callback_on_new_best=stop_callback,
                             eval_freq=10000,
                             best_model_save_path=save_path,
                             verbose=1)

In [66]:
log_path, save_path

('training/logs', 'training/save')

In [67]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [68]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to training/logs/PPO_13
-----------------------------
| time/              |      |
|    fps             | 326  |
|    iterations      | 1    |
|    time_elapsed    | 6    |
|    total_timesteps | 2048 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 254          |
|    iterations           | 2            |
|    time_elapsed         | 16           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0077076526 |
|    clip_fraction        | 0.0633       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.687       |
|    explained_variance   | -0.00035     |
|    learning_rate        | 0.0003       |
|    loss                 | 7.97         |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.00852     |
|    value_loss           | 59.4         |
---------------------------

In [69]:
#!tensorboard --logdir './training/logs/' --bind_all

In [70]:
net_arch = dict(pi=[128,128,128,128], vf=[128,128,128,128])

In [71]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path, policy_kwargs={'net_arch':net_arch})

Using cpu device


In [72]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to training/logs/PPO_14
-----------------------------
| time/              |      |
|    fps             | 266  |
|    iterations      | 1    |
|    time_elapsed    | 7    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 178         |
|    iterations           | 2           |
|    time_elapsed         | 22          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.014335567 |
|    clip_fraction        | 0.208       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | 0.00414     |
|    learning_rate        | 0.0003      |
|    loss                 | 2.55        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.023      |
|    value_loss           | 19.9        |
-----------------------------------------
--

In [73]:
from stable_baselines3 import DQN

In [74]:
model = DQN('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [75]:
model.learn(total_timesteps=20000)

Logging to training/logs/DQN_2
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.958    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 589      |
|    time_elapsed     | 0        |
|    total_timesteps  | 88       |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.923    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 656      |
|    time_elapsed     | 0        |
|    total_timesteps  | 162      |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.877    |
| time/               |          |
|    episodes         | 12       |
|    fps              | 367      |
|    time_elapsed     | 0        |
|    total_timesteps  | 259      |
----------------------------------
------------------------

In [76]:
DQN_Path = os.path.join('training','save','DQN_Model_Cartpole')
DQN_Path

'training/save/DQN_Model_Cartpole'

In [77]:
model.save(DQN_Path)

In [78]:
del model

In [79]:
model = DQN.load(DQN_Path, env=env)

In [80]:
del model